# Generated by Django 3.2.12 on 2022-11-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distanceBasePrice', models.CharField(max_length=200)),
                ('distanceAdditionalPrice', models.CharField(max_length=200)),
                ('timeMultiplierFactor', models.CharField(max_length=200)),
            ],
        ),
    ]
