# Generated by Django 3.2.12 on 2022-11-07 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='distance',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
