# Generated by Django 3.2.12 on 2022-11-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20221107_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingconfig',
            name='id',
            field=models.IntegerField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
